# Generated by Django 4.1.4 on 2022-12-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='score',
        ),
    ]
