# Generated by Django 4.1.4 on 2022-12-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dog', '0002_remove_photo_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
