# Generated by Django 4.1.4 on 2023-01-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dog', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='downloads',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
